### ISSUE TITLE
Main box lighter in color than other containers

### ISSUE THREAD

**Issue by radiohotline** [adriankarlen/textfox#128]
This is a sudden issue. It was normal before. The theme follows my GTK theme, I believe. I haven't explicitly edited the css colors. I haven't messed with the GTK css colors either.

![Image](https://github.com/user-attachments/assets/d583487b-bfdd-48bf-bc9e-382301eced5e)

**Comment by adriankarlen** [comment]
Are you using the Firefox Color extension?

**Comment by radiohotline** [comment]
![Image](https://github.com/user-attachments/assets/743c1ed5-d9a9-461f-8bce-975eedd95645)

I have installed textfox in a fresh Firefox installation on Artix. I have no extensions other than sidebery installed, and the problem happened again.

**Comment by katawajojo** [comment]
Can verify this happens with a fresh install of Firefox. The lighter color for the main container is actually following the color used for tabs. If the sidebar is enabled in Firefox, this color is also used for the background of that container as well.

This same issue happens to the sidebar with Floorp, but then the background of the "main" box follows the default Firefox Dark/Light color.

**Comment by adriankarlen** [comment]
I've pushed a change that hopefully could fix it https://github.com/adriankarlen/textfox/pull/135

**Comment by katawajojo** [comment]
> I've pushed a change that hopefully could fix it [#135](https://github.com/adriankarlen/textfox/pull/135)

Just tested, and the problem still persists. I'm currently running on Windows 11, but I can also go test on my Linux install.

**Comment by adriankarlen** [comment]
Alright.. I think the easiest thing for this would be for someone experiencing this issue to to inspect the browser using the Browser toolbox and find where the bg is being set wrongly. 

I would like to add that the only fully supported way to "theme" textfox is via the Firefox Color extension, using store themes or pywallfox is not on my radar to support.

**Comment by katawajojo** [comment]
so it looks like it's caused by `content-area.css:61` 

`chrome://browser/skin/tabbrowser/content-area.css`
```
#browser:not(.browser-toolbox-background) {
  :root[lwtheme] & {
    background-color: var(--lwt-accent-color);
    background-image: linear-gradient(var(--toolbar-bgcolor), var(--toolbar-bgcolor));
  }
}
```

The `background-image` entry here is what causes the color to be displayed the same as the tabs.
To verify as well, this issue happens when not even using a theme or Firefox Color. Base Dark and Light themes have this same behavior.

**Comment by radiohotline** [comment]
This issue is resolved in the latest version of Textfox and Firefox on Artix. Another issue appeared with the latest Firefox update however. It's that the search box is the one that's lighter now. Should I open a new issue?
