### ISSUE TITLE
Cannot bookmark pages

### ISSUE THREAD

**Issue by dovbaeb** [adriankarlen/textfox#77]
I'm usually using Crtl+D to bookmark the current page I'm using. But with textfox the window does not appear and I'm unable to proceed. I have to open the bookmark bar, and the darg and drop the tab in the bookmark bar manually. Any ideas ?

**Comment by adriankarlen** [comment]
Hi, I can see that this functionality seems to be broken by the theme, will try to investigate on what causes it, thanks for the report!

**Comment by dovbaeb** [comment]
Hi, I tried a few things, and I found out that for some reason, bookmarking in this way still works with meta pages (new tab, setting pages) but not on actual websites, if that helps.

**Comment by justyeethan** [comment]
I have a theory about this, and I think it's because the bookmarks popup also has an id of #identity-box. I'm not sure why bookmarking still works on meta pages for you, but at least for me it doesn't seem to work. I ended up playing around with this, and once I removed #identity-box from navbar.css, the popup ended up showing up and working. 

Maybe we could add additional styling for this?

**Comment by adriankarlen** [comment]
@dovbaeb I've merged a PR now that seemed to fix this issue for me. Could you test if the latest version of the theme resolves the issue for you?

If not I might just give up on hiding the icon all together.

**Comment by keenbanned** [comment]
@adriankarlen 
I'm using the latest version, and seemingly the bookmark new page window is still not able to be shown.

**Comment by adriankarlen** [comment]
Will take a look when I get the time

**Comment by adriankarlen** [comment]
@keenbanned this issue should definitely be resolved now in the related PR.
